

# generate fecundity rates
getLambdas = function(temperature,fec_Tmu,fec_Tsigma,fec_max){
    # temperature is a time series (vector) of T values
    # fec.Tmu is a vector of optimal temperatures (one value for each genotype)
    # fec.Tsigma is a vector of standard deviations for the temperature niche of each genotype
    L <- matrix(NA,nrow=length(temperature),ncol=length(fec_Tmu))
    for(i in 1:length(fec_Tmu)){
      L[,i] <- dnorm(temperature,fec_Tmu[i],fec_Tsigma[i])
      scalar <- fec_max[i]/dnorm(fec_Tmu[i],fec_Tmu[i],fec_Tsigma[i])
      L[,i] <- scalar*L[,i]
    }
    return(L)
}

# the next three functions make up the diploid model
newSeeds = function(N,lambda,alpha,G){
    # calculate the number of seeds produced by each genotype

  	# N = vector of length 3 giving each population at time t
  	# lambda = vector of the 3 genotype's fecundities
    # alpha is a 3x3 matrix of competition coefficients
  	# G = vector of length 3 of each genotype's germination rate
  	# output = vector (3) giving # seeds produced by each genotype at time t+1
    
    AA = lambda[1]*N[1]/(1+alpha[1,1]*N[1]+alpha[1,2]*N[2]+alpha[1,3]*N[3])
  	Aa = lambda[2]*N[2]/(1+alpha[2,1]*N[1]+alpha[2,2]*N[2]+alpha[2,3]*N[3])
    aa = lambda[3]*N[3]/(1+alpha[3,1]*N[1]+alpha[3,2]*N[2]+alpha[3,3]*N[3])
  	return(c(AA,Aa,aa))

}
  
getPhi<-function(seeds){
  # seeds is a vector of dim=3 containing the seeds produced by each genotpye (calculated in newSeeds() )
  phi<-numeric(2)   # create vector to store homozygote sqrt(frequencies)
  bigT<-sum(seeds)  # total seeds produced by all genotypes
  phi[1]<-(seeds[1] + seeds[2]/2)/bigT
  phi[2]<-1-phi[1] 
  return(phi)
}

diploid = function(N,seeds,phi){
    # This is an annual plant model, so it tracks
    # populations as numbers of seeds

  	# N = vector of length 3 giving each genotype's density at time t
    # G = vector of length 3 of each genotype's germination rate
  	# seedSurv = scalar giving the seedbank survival rate
    # seeds = vector (3) giving seeds produced by each genotype
    # phi = vector (2) giving frequency of homozygotes
  	# output = vector (3) giving density of each genotype at time t+1
    
    Plants = N
    bigT = sum(seeds)  # total seed production
    Fec=c(phi[1]^2*bigT, 2*phi[1]*phi[2]*bigT, phi[2]^2*bigT)
  	AA = Fec[1]
  	Aa = Fec[2]
    aa = Fec[3]
  	SB = c(AA,Aa,aa)
  	return(list(SB=SB,Plants=Plants,SP=Fec))
}

processOutput <- function(N,burn_in,temperature){
  # This functions take one simulation run and calculates per capita growth
  # rates for each genotype and for the whole population, 
  # then regresses the growth rates on the temperature time series
  
  # N is generated by the annual plant model
  # burn.in is the number of time steps at the start of the simulation to discard
  # temperature is the time series of temperature
  
  totTime <- NROW(N)
  N<-as.data.frame(N)
  N$Pop <- rowSums(N)
  means = colMeans(N[(burn_in+1):totTime,])
  pcgr = log(N[(burn_in+1):totTime,]/N[burn_in:(totTime-1),])  # calculate genotype level per capita growth rate
  temperature = temperature[(burn_in+1):totTime] # we index temperature at the start of the t to t+1 interval
    
  # do regressions
  regs <- data.frame("Genotype"=names(N),"Intercept"=numeric(NCOL(pcgr)),"Slope"=numeric(NCOL(pcgr)))
  for(i in 1:NCOL(pcgr)){
    keep<-which(!is.na(pcgr[,i]) & abs(pcgr[,i]) < Inf)
    if(length(keep)>2){
      tmp <- lm(pcgr[keep,i]~temperature[keep])  
      regs[i,2:3] <- coef(tmp)      
    }
  }
  
  # return mean number of individuals, time series, per capita growth rates, and regression coefs for each genotype
  # and whole population
  return(list(N=N,temperature=temperature,means=means,pcgr=pcgr,regs=regs))

}
